CREATE TABLE IF NOT EXISTS `s3_backup` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `s3_bucket` VARCHAR(100) NOT NULL,
  `s3_path` VARCHAR(300) NOT NULL,
  `local_path` VARCHAR(300) NOT NULL,
  `size` INT(10) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
